name: Create Scratch
on: 
  workflow_dispatch:
      inputs:
        alias:
          description: Alias
          required: true
        email:
          description: Email
          required: true
        description:
          description: Description
        duration_days:
          description: Duration Days
          default: '30'
          required: true
        
jobs:
  create_scratch:
    name: Create Scratch based on Org Shape
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authorize DevHub
        run: |
          echo ${{ secrets.SFDX_AUTHURL_PDEVHUB }} | sf org login sfdx-url --sfdx-url-stdin
      - name: Create Scratch Org
        run: |
          sf org create scratch --set-default --definition-file config/project-scratch-def.json --target-dev-hub ${{ secrets.SFDX_USERNAME_PDEVHUB }} --no-namespace --duration-days  ${{ github.event.inputs.duration_days }}  --wait 30 --description ${{ github.event.inputs.description }} --admin-email ${{ github.event.inputs.email }} --source-org ${{ secrets.SFDX_ORGID_PDEVHUB }} --alias ${{ github.event.inputs.alias }}
          sf org generate password --target-org ${{ github.event.inputs.alias }}
          sf org display user --target-org ${{ github.event.inputs.alias }} | tee -a scratch-org-info.txt
          sf org logout --all --no-prompt
      - name: Store Scratch Org Information as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Store Scratch Org Info
          path: scratch-org-info.txt
      
        
      
        
